baseURL = "https://ironmaos.github.io/hugotester"
languageCode = "en-us"
title = "QigiBro QuickStart"
theme = "bootstrap-bp-hugo-startpage"
publishDir = "docs"

[params]
  description = "QigiBro QuickStart"
  #images = ["logo.jpg"]
  startPageColumns = false
  titleText = "QigiBro"
  welcomeText = "Better. Stronger. Faster. Welcome to Qigital Broduction."

[[params.searchEngines]]
  name = "QymerNet"
  activated = false
  url = "www.google.com"